import TagCloud from "TagCloud";
import React, { useState, useEffect } from "react";

const Sphere = () => {
  const [count, setCount] = useState(0);
  useEffect(() => {
    setCount(count + 1);
    const container = ".tagcloud";
    const texts = [
      "HTML",
      "CSS",
      "SCSS",
      "SAAS",
      "LESS",
      "TAILWIND",
      "JAVA",
      "JS",
      "REACT",
      "NEXT",
      "VITE",
      "MUI",
      "JEST",
      "DSA",
      "GIT HUB",
      "GIT",
      "ES6",
      "PWAs",
      "GIT",
      "MySql",
      "NODEJS",
      "EXPRESS",
      "REST",
      "API",
      "MONGODB",
      "MONGOOSE",
      "HTML",
      "CSS",
      "SCSS",
      "SAAS",
      "LESS",
      "TAILWIND",
      "JAVA",
      "JS",
      "REACT",
      "NEXT",
      "VITE",
      "MUI",
      "JEST",
      "DSA",
      "GIT HUB",
      "GIT",
      "ES6",
      "PWAs",
      "GIT",
      "MySql",
      "NODEJS",
      "EXPRESS",
      "REST",
      "API",
      "MONGODB",
      "MONGOOSE",
      "HTML",
      "CSS",
      "SCSS",
      "SAAS",
      "LESS",
      "TAILWIND",
      "JAVA",
      "JS",
      "REACT",
      "NEXT",
      "VITE",
      "MUI",
      "JEST",
      "DSA",
      "GIT HUB",
      "GIT",
      "ES6",
      "PWAs",
      "GIT",
      "MySql",
      "NODEJS",
      "EXPRESS",
      "REST",
      "API",
      "MONGODB",
      "MONGOOSE",
      "HTML",
      "CSS",
      "SCSS",
      "SAAS",
      "LESS",
      "TAILWIND",
      "JAVA",
      "JS",
      "REACT",
      "NEXT",
      "VITE",
      "MUI",
      "JEST",
      "DSA",
      "GIT HUB",
      "GIT",
      "ES6",
      "PWAs",
      "GIT",
      "MySql",
      "NODEJS",
      "EXPRESS",
      "REST",
      "API",
      "PYTHON",
      "DJANGO",
      "AI/ML",
    ];
    const options = {
      radius: 350, 
      maxSpeed: "fast",
      initSpeed: "fast",

      keep: true,
    };
    TagCloud(container, texts, options);
  }, []);

  console.log(count);

  return (
    // <div className="text-accent font-semibold">
    <div className="tagcloud text-accent"></div>
    // </div>
  );
};
export default Sphere;
